id: IDE7E71AD
legacy_id: P000347
ocr_import_info:
  bdrc_scan_id: W23935
  source: bdrc
  ocr_info:
    timestamp: '2020-03-14T10:07:55'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T05:19:35.991940+00:00'
last_modified: 2022-09-02 13:20:02.920954
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23935
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23935
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མཁས་གྲུབ་ཆེན་པོ་བསོད་ནམས་བློ་གྲོས་ཀྱི་རྣམ་པར་ཐར་པ་མཐོང་བ་དོན་ལྡན་དད་པའི་གསལ་འདེབས་དང་གསང་བའི་རྣམ་ཐར་དང་མགུར་འབུམ།
  author: སྟར་པ་རྡོ་རྗེ་དཔལ་བཟང་།
statistics:
  ocr_word_mean_confidence_index: 0.6832005018987342
  ocr_word_median_confidence_index: 0.7599999904632568
quality: null
bases:
  I3579:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3579
      total_pages: 510
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3579.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.6832005018987342
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
